#!/usr/bin/env node
/* ============================================================
   BUILD
   Renders every page from src/ into plain HTML files at the repo
   root, where GitHub Pages serves them. No dependencies: Node 18+.

     node scripts/build.mjs           build
     node scripts/build.mjs --serve   build, then serve on :8000
                                      with GitHub Pages URL rules

   The generated .html files are committed. Edit src/, not them.

   After writing, the build checks that every internal link and
   in-page anchor points at something that exists, and fails if
   one doesn't.
   ============================================================ */

import { createHash } from 'node:crypto';
import { createServer } from 'node:http';
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, extname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { layout } from '../src/layout.mjs';
import { site } from '../src/site.mjs';
import { services } from '../src/data/services.mjs';
import { areas } from '../src/data/areas.mjs';
import { servicePage } from '../src/templates/service.mjs';
import { areaPage } from '../src/templates/area.mjs';
import { homePage } from '../src/pages/home.mjs';
import { servicesIndexPage } from '../src/pages/services-index.mjs';
import { serviceAreaIndexPage } from '../src/pages/service-area-index.mjs';
import { aboutPage } from '../src/pages/about.mjs';
import { contactPage } from '../src/pages/contact.mjs';
import { bookingPage } from '../src/pages/booking.mjs';
import { reviewsPage, privacyPage, notFoundPage } from '../src/pages/misc.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const GENERATED = '<!-- Generated by scripts/build.mjs from src/. Edit the source, not this file. -->\n';

/* ------------------------------------------------------------
   Assets, fingerprinted by content so a deploy is never served
   a stale stylesheet from cache.
   ------------------------------------------------------------ */
function fingerprint(rel) {
  const hash = createHash('sha256').update(readFileSync(join(ROOT, rel))).digest('hex').slice(0, 10);
  return `/${rel}?v=${hash}`;
}
const assets = {
  css: fingerprint('css/styles.css'),
  js: fingerprint('js/main.js'),
  form: fingerprint('js/form.js'),
};

/* ------------------------------------------------------------
   Pages
   ------------------------------------------------------------ */
const pages = [
  homePage(),
  servicesIndexPage(),
  ...services.map(servicePage),
  serviceAreaIndexPage(),
  ...areas.map(areaPage),
  aboutPage(),
  contactPage(assets),
  bookingPage(assets),
  reviewsPage(),
  privacyPage(),
  notFoundPage(),
];

function outputPath(urlPath) {
  if (urlPath === '/') return 'index.html';
  if (urlPath.endsWith('/')) return `${urlPath.slice(1)}index.html`;
  return `${urlPath.slice(1)}.html`;
}

function write(rel, content) {
  const file = join(ROOT, rel);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, content);
}

for (const page of pages) {
  const doc = layout(page, assets).replace('<head>\n', `<head>\n${GENERATED}`);
  write(outputPath(page.path), tidy(doc));
}

/* The service area used to live at /servicearea. Keep the old URL
   working for anyone who bookmarked or linked it. */
write('servicearea.html', redirect('/service-area/'));

/* ------------------------------------------------------------
   Sitemap and robots
   ------------------------------------------------------------ */
const today = new Date().toISOString().slice(0, 10);
const indexable = pages.filter((p) => !p.noindex);
write('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${indexable.map((p) => `  <url><loc>${site.url}${p.path}</loc><lastmod>${today}</lastmod></url>`).join('\n')}
</urlset>
`);
write('robots.txt', `User-agent: *
Allow: /

Sitemap: ${site.url}/sitemap.xml
`);

console.log(`Built ${pages.length} pages.`);

/* ------------------------------------------------------------
   Link check
   ------------------------------------------------------------ */
const problems = checkLinks(pages.map((p) => outputPath(p.path)));
if (problems.length) {
  console.error(`\n${problems.length} broken internal link(s):`);
  problems.forEach((p) => console.error(`  ${p}`));
  process.exit(1);
}
console.log('Internal links OK.');

if (process.argv.includes('--serve')) serve(8000);

/* ============================================================ */

function redirect(to) {
  return `<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="utf-8">
<title>Moved | ${site.name}</title>
<link rel="canonical" href="${site.url}${to}">
<meta name="robots" content="noindex">
<meta http-equiv="refresh" content="0; url=${to}">
<script>location.replace(${JSON.stringify(to)} + location.hash);</script>
</head>
<body>
<p>This page has moved to <a href="${to}">${site.url}${to}</a>.</p>
</body>
</html>
`;
}

/* Collapse the blank lines template interpolation leaves behind. */
function tidy(doc) {
  return doc.replace(/[ \t]+\n/g, '\n').replace(/\n{3,}/g, '\n\n');
}

/* Resolve a site path the way GitHub Pages does. */
function resolveFile(urlPath) {
  const clean = decodeURIComponent(urlPath.split(/[?#]/)[0]);
  const candidates = clean.endsWith('/')
    ? [join(clean, 'index.html')]
    : [clean, `${clean}.html`, join(clean, 'index.html')];
  for (const c of candidates) {
    const file = join(ROOT, c);
    if (existsSync(file) && statSync(file).isFile()) return file;
  }
  return null;
}

function checkLinks(files) {
  const problems = [];
  const idsCache = new Map();
  const idsOf = (file) => {
    if (!idsCache.has(file)) {
      const src = readFileSync(file, 'utf8');
      idsCache.set(file, new Set([...src.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1])));
    }
    return idsCache.get(file);
  };

  for (const rel of files) {
    const file = join(ROOT, rel);
    const src = readFileSync(file, 'utf8');
    for (const [, href] of src.matchAll(/\s(?:href|src)="([^"]+)"/g)) {
      if (/^(https?:|mailto:|tel:|sms:|data:)/.test(href)) continue;
      const [pathPart, hash] = href.split('#');
      const target = pathPart === '' ? file : resolveFile(pathPart);
      if (!target) { problems.push(`${rel}: ${href}`); continue; }
      if (hash && target.endsWith('.html') && !idsOf(target).has(hash)) problems.push(`${rel}: ${href} (no #${hash})`);
    }
    for (const [, set] of src.matchAll(/\ssrcset="([^"]+)"/g)) {
      for (const part of set.split(',')) {
        const url = part.trim().split(/\s+/)[0];
        if (!resolveFile(url)) problems.push(`${rel}: ${url}`);
      }
    }
  }
  return problems;
}

/* Local server with GitHub Pages' URL resolution: extensionless
   paths map to .html, directories to index.html, misses to 404. */
function serve(port) {
  const types = {
    '.html': 'text/html; charset=utf-8', '.css': 'text/css', '.js': 'text/javascript',
    '.json': 'application/json', '.xml': 'application/xml', '.txt': 'text/plain',
    '.jpg': 'image/jpeg', '.png': 'image/png', '.webp': 'image/webp', '.svg': 'image/svg+xml',
    '.ico': 'image/x-icon', '.woff2': 'font/woff2', '.pdf': 'application/pdf',
  };
  createServer((req, res) => {
    const url = new URL(req.url, 'http://localhost');
    let file = resolveFile(url.pathname);
    // A directory without a trailing slash redirects, as on GitHub Pages.
    if (file && file.endsWith('index.html') && !url.pathname.endsWith('/') && url.pathname !== '/') {
      const dir = join(ROOT, url.pathname);
      if (existsSync(dir) && statSync(dir).isDirectory()) {
        res.writeHead(301, { Location: `${url.pathname}/${url.search}` });
        return res.end();
      }
    }
    const status = file ? 200 : 404;
    file ??= join(ROOT, '404.html');
    res.writeHead(status, { 'Content-Type': types[extname(file)] ?? 'application/octet-stream' });
    res.end(readFileSync(file));
  }).listen(port, () => console.log(`Serving on http://localhost:${port}`));
}
